apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: pi
spec:
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 1
  schedule: "*/1 * * * *"
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            parent: "cronjobpi"
        spec:
          containers:
          - name: pi
            image: registry.redhat.io/rhscl/perl-526-rhel7
            command: ["perl", "-Mbignum=bpi", "-wle", "print bpi(2000)"]
            resources:
              limits:
                cpu: 500m
                memory: 1Gi
              requests:
                cpu: 100m
                memory: 1Gi
          restartPolicy: OnFailure

