apiVersion: v1
kind: ClusterResourceQuota
metadata:
  name: resources
spec:
  quota: 
    hard:
      requests.cpu: "12"
      limits.cpu: "12"
      requests.memory: "24Gi"
      limits.memory: "24Gi"
  selector:
    annotations: 
      openshift.io/requester: system:serviceaccount:httpd:clusterquota
    labels: null
